/**
 * API Client cho Phân hệ 3: Quản lý Điều trị Nội trú
 * Barrel re-export — sub-modules live in ./inpatient/
 */

export type { PagedResult } from './inpatient/_shared';
export * from './inpatient/ward-bed';
export * from './inpatient/admission';
export * from './inpatient/orders';
export * from './inpatient/prescription-nutrition';
export * from './inpatient/treatment';
export * from './inpatient/discharge-report';

// Re-import all functions for the convenience default export
import {
  getWardLayout,
  getRoomLayouts,
  getBedLayouts,
  getSharedBedPatients,
  getWardColorConfig,
  updateWardColorConfig,
  assignBed,
  transferBed,
  registerSharedBed,
  releaseBed,
  getBedStatus,
} from './inpatient/ward-bed';

import {
  getInpatientList,
  admitFromOpd,
  admitFromDepartment,
  createCombinedTreatment,
  getCombinedTreatments,
  completeCombinedTreatment,
  transferDepartment,
  requestSpecialtyConsult,
  getSpecialtyConsultRequests,
  completeSpecialtyConsult,
  transferToScheduledSurgery,
  transferToEmergencySurgery,
  updateInsurance,
  checkInsuranceReferral,
  convertToFeePaying,
  getDailyOrderSummary,
  getLabResults,
  printLabResults,
  getDepartmentFeeOverview,
  getPatientFee,
  createDepositRequest,
  getDepositRequests,
  checkTransferWarnings,
} from './inpatient/admission';

import {
  getDiagnosisFromRecord,
  getServiceTree,
  searchServices,
  createServiceOrder,
  updateServiceOrder,
  deleteServiceOrder,
  getServiceOrders,
  getServiceOrderById,
  createServiceGroupTemplate,
  getServiceGroupTemplates,
  orderByTemplate,
  orderByPackage,
  markServiceAsUrgent,
  checkServiceOrderWarnings,
  printServiceOrder,
  getAdmissionServiceRequests,
  cancelServiceRequests,
  updateServiceRequestPaymentType,
} from './inpatient/orders';

import {
  searchMedicines,
  getMedicineContraindications,
  getMedicineStock,
  createPrescription,
  updatePrescription,
  deletePrescription,
  getPrescriptions,
  getPrescriptionById,
  createEmergencyCabinetPrescription,
  getEmergencyCabinets,
  checkPrescriptionWarnings,
  getPrescriptionTemplates,
  createPrescriptionTemplate,
  prescribeByTemplate,
  createMedicineOrderSummary,
  getMedicineOrderSummaries,
  printMedicineOrderSummary,
  createNutritionOrder,
  updateNutritionOrder,
  getNutritionOrders,
  getNutritionSummary,
  printNutritionSummary,
} from './inpatient/prescription-nutrition';

import {
  getAutoTreatmentSummary,
  getTreatmentStatAggregate,
  createTreatmentSheet,
  updateTreatmentSheet,
  getTreatmentSheets,
  printTreatmentSheet,
  createVitalSigns,
  getVitalSignsList,
  getVitalSignsChart,
  createConsultation,
  getConsultations,
  completeConsultation,
  approveConsultation,
  printConsultation,
  createNursingCareSheet,
  getNursingCareSheets,
  createInfusionRecord,
  completeInfusion,
  calculateInfusionEndTime,
  createBloodTransfusion,
  recordTransfusionReaction,
  createDrugReactionRecord,
  getDrugReactionRecords,
} from './inpatient/treatment';

import {
  checkPreDischarge,
  dischargePatient,
  cancelDischarge,
  printDischargeCertificate,
  printReferralCertificate,
  printServiceDisclosure,
  printMedicineDisclosure,
  getBillingStatement6556,
  printBillingStatement6556,
  getDepartmentRevenueReport,
  getTreatmentActivityReport,
  getRegister4069,
  printRegister4069,
  getMedicineSupplyUsageReport,
  createNewborn,
  getNewborns,
  updateNewborn,
  dischargeNewborn,
  createHemodialysis,
  getHemodialysisSessions,
  updateHemodialysis,
  deleteHemodialysis,
} from './inpatient/discharge-report';

// Default export for convenience
export default {
  // Ward Layout
  getWardLayout,
  getRoomLayouts,
  getBedLayouts,
  getSharedBedPatients,
  getWardColorConfig,
  updateWardColorConfig,

  // Patient Management
  getInpatientList,
  admitFromOpd,
  admitFromDepartment,
  createCombinedTreatment,
  getCombinedTreatments,
  completeCombinedTreatment,
  transferDepartment,
  requestSpecialtyConsult,
  getSpecialtyConsultRequests,
  completeSpecialtyConsult,
  transferToScheduledSurgery,
  transferToEmergencySurgery,
  updateInsurance,
  checkInsuranceReferral,
  convertToFeePaying,
  assignBed,
  transferBed,
  registerSharedBed,
  releaseBed,
  getBedStatus,
  getDailyOrderSummary,
  getLabResults,
  printLabResults,
  getDepartmentFeeOverview,
  getPatientFee,
  createDepositRequest,
  getDepositRequests,
  checkTransferWarnings,

  // Service Orders
  getDiagnosisFromRecord,
  getServiceTree,
  searchServices,
  createServiceOrder,
  updateServiceOrder,
  deleteServiceOrder,
  getServiceOrders,
  getServiceOrderById,
  createServiceGroupTemplate,
  getServiceGroupTemplates,
  orderByTemplate,
  orderByPackage,
  markServiceAsUrgent,
  checkServiceOrderWarnings,
  printServiceOrder,

  // Prescriptions
  searchMedicines,
  getMedicineContraindications,
  getMedicineStock,
  createPrescription,
  updatePrescription,
  deletePrescription,
  getPrescriptions,
  getPrescriptionById,
  createEmergencyCabinetPrescription,
  getEmergencyCabinets,
  checkPrescriptionWarnings,
  getPrescriptionTemplates,
  createPrescriptionTemplate,
  prescribeByTemplate,
  createMedicineOrderSummary,
  getMedicineOrderSummaries,
  printMedicineOrderSummary,

  // Nutrition
  createNutritionOrder,
  updateNutritionOrder,
  getNutritionOrders,
  getNutritionSummary,
  printNutritionSummary,

  // Treatment Info
  createTreatmentSheet,
  updateTreatmentSheet,
  getTreatmentSheets,
  printTreatmentSheet,
  createVitalSigns,
  getVitalSignsList,
  getVitalSignsChart,
  createConsultation,
  getConsultations,
  completeConsultation,
  approveConsultation,
  printConsultation,
  createNursingCareSheet,
  getNursingCareSheets,
  createInfusionRecord,
  completeInfusion,
  calculateInfusionEndTime,
  createBloodTransfusion,
  recordTransfusionReaction,
  createDrugReactionRecord,
  getDrugReactionRecords,

  // G-08 + G-15: CLS ServiceRequests
  getAdmissionServiceRequests,
  cancelServiceRequests,
  updateServiceRequestPaymentType,

  // Discharge
  checkPreDischarge,
  dischargePatient,
  cancelDischarge,
  printDischargeCertificate,
  printReferralCertificate,
  printServiceDisclosure,
  printMedicineDisclosure,
  getBillingStatement6556,
  printBillingStatement6556,

  // Reports
  getDepartmentRevenueReport,
  getTreatmentActivityReport,
  getRegister4069,
  printRegister4069,
  getMedicineSupplyUsageReport,

  // Newborn (#50-54)
  createNewborn,
  getNewborns,
  updateNewborn,
  dischargeNewborn,

  // Hemodialysis (#148)
  createHemodialysis,
  getHemodialysisSessions,
  updateHemodialysis,
  deleteHemodialysis,
};
