export const SPECIALTY_FORM_MAP: Record<string, { component: string; title: string }> = {
  'MS:01/BV1': { component: 'InternalMedicineMRPrint', title: 'Benh an Noi khoa' },
  'MS:03/BV1': { component: 'InfectiousDiseaseMRPrint', title: 'Benh an Truyen nhiem' },
  'MS:04/BV1': { component: 'GynecologyMRPrint', title: 'Benh an Phu khoa' },
  'MS:07/BV1': { component: 'PsychiatryMRPrint', title: 'Benh an Tam than' },
  'MS:08/BV1': { component: 'DermatologyMRPrint', title: 'Benh an Da lieu' },
  'MS:09/BV1': { component: 'HematologyMRPrint', title: 'Benh an Huyet hoc - Truyen mau' },
  'MS:10/BV1': { component: 'SurgicalMRPrint', title: 'Benh an Ngoai khoa' },
  'MS:11/BV1': { component: 'BurnsMRPrint', title: 'Benh an Bong' },
  'MS:12/BV1': { component: 'OncologyMRPrint', title: 'Benh an Ung buou' },
  'MS:13/BV1': { component: 'DentalMRPrint', title: 'Benh an Rang Ham Mat' },
  'MS:14/BV1': { component: 'ENTMRPrint', title: 'Benh an Tai Mui Hong' },
  'MS:15/BV1': { component: 'OutpatientGeneralMRPrint', title: 'Benh an Ngoai tru chung' },
  'MS:16/BV1': { component: 'OutpatientDentalMRPrint', title: 'Benh an Ngoai tru Rang Ham Mat' },
  'MS:17/BV1': { component: 'CommuneHealthMRPrint', title: 'Benh an tuyen xa/phuong' },
  'MS:18/BV1': { component: 'TraditionalMedInpatientMRPrint', title: 'Benh an Noi tru Y hoc co truyen' },
  'MS:19/BV1': { component: 'TraditionalMedOutpatientMRPrint', title: 'Benh an Ngoai tru Y hoc co truyen' },
  'MS:20/BV1': { component: 'PediatricTCMMRPrint', title: 'Benh an Noi tru Nhi Y hoc co truyen' },
  'MS:21/BV1': { component: 'EyeTraumaMRPrint', title: 'Benh an Mat - Chan thuong' },
  'MS:22/BV1': { component: 'EyeAnteriorMRPrint', title: 'Benh an Mat - Ban phan truoc' },
  'MS:23/BV1': { component: 'EyePosteriorMRPrint', title: 'Benh an Mat - Day mat' },
  'MS:24/BV1': { component: 'EyeGlaucomaMRPrint', title: 'Benh an Mat - Glocom' },
  'MS:25/BV1': { component: 'EyeStrabismusMRPrint', title: 'Benh an Mat - Lac' },
  'MS:26/BV1': { component: 'PediatricEyeMRPrint', title: 'Benh an Mat tre em' },
  'MS:27/BV1': { component: 'RehabilitationMRPrint', title: 'Benh an Phuc hoi chuc nang' },
  'MS:28/BV1': { component: 'PediatricRehabMRPrint', title: 'Benh an Phuc hoi chuc nang Nhi' },
  'MS:29/BV1': { component: 'OutpatientRehabMRPrint', title: 'Benh an Ngoai tru Phuc hoi chuc nang' },
  'MS:03/BV2': { component: 'OnDemandExamPrint', title: 'Giay kham benh theo yeu cau' },
  'MS:04/BV2': { component: 'SpecialtyExamPrint', title: 'Phieu kham chuyen khoa' },
  'MS:37/BV2': { component: 'NursingCareLevel1Print', title: 'Phieu cham soc cap 1' },
  'MS:38/BV2': { component: 'NursingCareLevel2Print', title: 'Phieu cham soc cap 2' },
};
