-- Fix missing columns for 6 tables
-- VaccinationRecords: entity has VaccineCode missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='VaccinationRecords' AND COLUMN_NAME='VaccineCode')
    ALTER TABLE VaccinationRecords ADD VaccineCode NVARCHAR(50) NULL;
GO

-- SchoolHealthExams: missing columns from entity
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='SchoolCode')
    ALTER TABLE SchoolHealthExams ADD SchoolCode NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='NutritionStatus')
    ALTER TABLE SchoolHealthExams ADD NutritionStatus NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='HasVisionProblem')
    ALTER TABLE SchoolHealthExams ADD HasVisionProblem BIT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='SpineResult')
    ALTER TABLE SchoolHealthExams ADD SpineResult NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='SkinResult')
    ALTER TABLE SchoolHealthExams ADD SkinResult NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='HeartLungResult')
    ALTER TABLE SchoolHealthExams ADD HeartLungResult NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='MentalHealthResult')
    ALTER TABLE SchoolHealthExams ADD MentalHealthResult NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='OverallResult')
    ALTER TABLE SchoolHealthExams ADD OverallResult NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='Recommendations')
    ALTER TABLE SchoolHealthExams ADD Recommendations NVARCHAR(MAX) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SchoolHealthExams' AND COLUMN_NAME='Status')
    ALTER TABLE SchoolHealthExams ADD Status INT NOT NULL DEFAULT 0;
GO

-- OccupationalHealthExams: missing columns from entity
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='PatientId')
    ALTER TABLE OccupationalHealthExams ADD PatientId UNIQUEIDENTIFIER NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='ExamType')
    ALTER TABLE OccupationalHealthExams ADD ExamType NVARCHAR(50) NOT NULL DEFAULT '';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='GeneralHealth')
    ALTER TABLE OccupationalHealthExams ADD GeneralHealth NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='RespiratoryResult')
    ALTER TABLE OccupationalHealthExams ADD RespiratoryResult NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='HearingResult')
    ALTER TABLE OccupationalHealthExams ADD HearingResult NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='VisionResult')
    ALTER TABLE OccupationalHealthExams ADD VisionResult NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='SkinResult')
    ALTER TABLE OccupationalHealthExams ADD SkinResult NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='LabResults')
    ALTER TABLE OccupationalHealthExams ADD LabResults NVARCHAR(MAX) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='XrayResult')
    ALTER TABLE OccupationalHealthExams ADD XrayResult NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OccupationalHealthExams' AND COLUMN_NAME='Status')
    ALTER TABLE OccupationalHealthExams ADD Status INT NOT NULL DEFAULT 0;
GO

-- MethadoneDosingRecords: missing columns from entity
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneDosingRecords' AND COLUMN_NAME='Witnessed')
    ALTER TABLE MethadoneDosingRecords ADD Witnessed BIT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneDosingRecords' AND COLUMN_NAME='TakeHome')
    ALTER TABLE MethadoneDosingRecords ADD TakeHome BIT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneDosingRecords' AND COLUMN_NAME='AdministeredBy')
    ALTER TABLE MethadoneDosingRecords ADD AdministeredBy NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneDosingRecords' AND COLUMN_NAME='Status')
    ALTER TABLE MethadoneDosingRecords ADD Status INT NOT NULL DEFAULT 0;
GO

-- MethadoneUrineTests: missing columns from entity
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='TestDate')
    ALTER TABLE MethadoneUrineTests ADD TestDate DATETIME2 NOT NULL DEFAULT GETDATE();
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='IsRandom')
    ALTER TABLE MethadoneUrineTests ADD IsRandom BIT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='Morphine')
    ALTER TABLE MethadoneUrineTests ADD Morphine NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='Amphetamine')
    ALTER TABLE MethadoneUrineTests ADD Amphetamine NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='Methamphetamine')
    ALTER TABLE MethadoneUrineTests ADD Methamphetamine NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='THC')
    ALTER TABLE MethadoneUrineTests ADD THC NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='Benzodiazepine')
    ALTER TABLE MethadoneUrineTests ADD Benzodiazepine NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='Methadone')
    ALTER TABLE MethadoneUrineTests ADD Methadone NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MethadoneUrineTests' AND COLUMN_NAME='OverallResult')
    ALTER TABLE MethadoneUrineTests ADD OverallResult NVARCHAR(100) NULL;
GO

PRINT 'All missing columns added successfully';
GO
