import type { RouteEntry } from './index';
import {
  ReceptionV2, OPDV2, OpdEditorV2, InpatientV2, PrescriptionV2, PrescriptionEditorV2,
  SurgeryV2, EMRV2, EmrEditorV2, EmrExtractV2, EmrDataTagsV2, TelemedicineV2, FollowUpV2,
  BookingManagementV2, TreatmentProtocolV2, ChronicDiseaseV2, TbHivManagementV2, ConsultationV2,
  ClinicalCatalogsV2, SpecialtyEMRV2, MedicalRecordArchiveV2, MedicalRecordPlanningV2,
  EmergencyDisasterV2, ConsultationRegisterV2, ObservationStayV2, ServiceRequeueV2, VideoConsultationV2,
  PharmacyV2, HospitalPharmacyV2, PharmacyStockInV2, PharmacyStockIssueV2, PharmacyApprovalV2,
  PharmacyStockTakeV2, MedicalSupplyV2, NutritionV2, RehabilitationV2, TraditionalMedicineV2,
  PharmacyCatalogsV2, DispensingCounterV2, ClinicalPharmacyCheckV2, InpatientDispensingV2,
  StockReportV2, OfficeSupplyApprovalV2,
  HealthCheckupV2, ImmunizationV2, EpidemiologyV2, SchoolHealthV2, OccupationalHealthV2,
  MethadoneTreatmentV2, FoodSafetyV2, CommunityHealthV2, HivManagementV2, HealthEducationV2,
  EnvironmentalHealthV2, PopulationHealthV2, ReproductiveHealthV2, MentalHealthV2,
  TraumaRegistryV2, MedicalForensicsV2,
} from '../lazy/clinical.lazy';

// Domain: clinical — menu groups clinical + support + public-health.
export const clinicalV2Routes: RouteEntry[] = [
  // --- clinical group ---
  { path: 'reception', Component: ReceptionV2, meta: { title: 'Tiếp đón', group: 'clinical' } },
  { path: 'opd', Component: OPDV2, meta: { title: 'Khám bệnh', group: 'clinical' } },
  { path: 'opd/edit', Component: OpdEditorV2, meta: { title: 'Khám bệnh (chỉnh sửa)', group: 'clinical' } },
  { path: 'ipd', Component: InpatientV2, meta: { title: 'Nội trú', group: 'clinical' } },
  { path: 'prescription', Component: PrescriptionV2, meta: { title: 'Kê đơn', group: 'clinical' } },
  { path: 'prescription/edit', Component: PrescriptionEditorV2, meta: { title: 'Kê đơn (chỉnh sửa)', group: 'clinical' } },
  { path: 'surgery', Component: SurgeryV2, meta: { title: 'Phẫu thuật', group: 'clinical' } },
  { path: 'emr', Component: EMRV2, meta: { title: 'Hồ sơ BA (EMR)', group: 'clinical' } },
  { path: 'emr/edit', Component: EmrEditorV2, meta: { title: 'EMR (chỉnh sửa)', group: 'clinical' } },
  { path: 'emr-extract', Component: EmrExtractV2, meta: { title: 'Trích lục bệnh án', group: 'clinical' } },
  { path: 'emr-data-tags', Component: EmrDataTagsV2, meta: { title: 'Thẻ dữ liệu EMR', group: 'clinical' } },
  { path: 'telemedicine', Component: TelemedicineV2, meta: { title: 'Khám từ xa', group: 'clinical' } },
  { path: 'follow-up', Component: FollowUpV2, meta: { title: 'Tái khám', group: 'clinical' } },
  { path: 'booking-management', Component: BookingManagementV2, meta: { title: 'Quản lý đặt lịch', group: 'clinical' } },
  { path: 'treatment-protocols', Component: TreatmentProtocolV2, meta: { title: 'Phác đồ điều trị', group: 'clinical' } },
  { path: 'chronic-disease', Component: ChronicDiseaseV2, meta: { title: 'Bệnh mạn tính', group: 'clinical' } },
  { path: 'tb-hiv', Component: TbHivManagementV2, meta: { title: 'Quản lý Lao/HIV', group: 'clinical' } },
  { path: 'consultation', Component: ConsultationV2, meta: { title: 'Hội chẩn', group: 'clinical' } },
  { path: 'doctor-portal', redirect: '/m/doctor-portal', meta: { title: 'Cổng bác sĩ', group: 'clinical' } },
  { path: 'clinical-catalogs', Component: ClinicalCatalogsV2, meta: { title: 'DM Lâm sàng', group: 'clinical' } },
  { path: 'specialty-emr', Component: SpecialtyEMRV2, meta: { title: 'BA chuyên khoa', group: 'clinical' } },
  { path: 'medical-record-archive', Component: MedicalRecordArchiveV2, meta: { title: 'Lưu trữ HSBA', group: 'clinical' } },
  { path: 'medical-record-planning', Component: MedicalRecordPlanningV2, meta: { title: 'Kế hoạch TH', group: 'clinical' } },
  // emergency-disaster: also appears in the integration menu; group follows the FIRST
  // menu match (clinical / 'Cấp cứu') per findGroupIdForPath — behavior-preserving.
  { path: 'emergency-disaster', Component: EmergencyDisasterV2, meta: { title: 'Cấp cứu', group: 'clinical' } },
  { path: 'consultation-register', Component: ConsultationRegisterV2, meta: { title: 'Sổ đăng ký hội chẩn', group: 'clinical' } },
  { path: 'observation-stay', Component: ObservationStayV2, meta: { title: 'Lưu theo dõi (Observation)', group: 'clinical' } },
  { path: 'service-requeue', Component: ServiceRequeueV2, meta: { title: 'Xếp lại hàng chờ DV', group: 'clinical' } },
  { path: 'video-consultation', Component: VideoConsultationV2, meta: { title: 'Hội chẩn video', group: 'clinical' } },
  { path: 'lite/reception', Component: ReceptionV2, meta: { title: 'Tiếp đón (lite)', group: 'clinical' } },
  { path: 'lite/opd', Component: OPDV2, meta: { title: 'Khám bệnh (lite)', group: 'clinical' } },
  { path: 'lite/ipd', Component: InpatientV2, meta: { title: 'Nội trú (lite)', group: 'clinical' } },
  { path: 'lite/prescription', Component: PrescriptionV2, meta: { title: 'Kê đơn (lite)', group: 'clinical' } },
  { path: 'lite/surgery', Component: SurgeryV2, meta: { title: 'Phẫu thuật (lite)', group: 'clinical' } },
  { path: 'lite/emr', Component: EMRV2, meta: { title: 'Hồ sơ BA EMR (lite)', group: 'clinical' } },

  // --- support group ---
  { path: 'pharmacy', Component: PharmacyV2, meta: { title: 'Nhà thuốc', group: 'support' } },
  { path: 'hospital-pharmacy', Component: HospitalPharmacyV2, meta: { title: 'Nhà thuốc bệnh viện', group: 'support' } },
  { path: 'pharmacy-stock-in', Component: PharmacyStockInV2, meta: { title: 'Nhập kho NCC', group: 'support' } },
  { path: 'pharmacy-stock-issue', Component: PharmacyStockIssueV2, meta: { title: 'Xuất kho', group: 'support' } },
  { path: 'pharmacy-approval', Component: PharmacyApprovalV2, meta: { title: 'Dự trù & Duyệt cấp phát', group: 'support' } },
  { path: 'pharmacy-stock-take', Component: PharmacyStockTakeV2, meta: { title: 'Kiểm kê kho', group: 'support' } },
  { path: 'medical-supply', Component: MedicalSupplyV2, meta: { title: 'Vật tư y tế', group: 'support' } },
  { path: 'nutrition', Component: NutritionV2, meta: { title: 'Dinh dưỡng', group: 'support' } },
  { path: 'rehabilitation', Component: RehabilitationV2, meta: { title: 'VLTL / PHCN', group: 'support' } },
  { path: 'traditional-medicine', Component: TraditionalMedicineV2, meta: { title: 'Y học cổ truyền', group: 'support' } },
  { path: 'pharmacy-catalogs', Component: PharmacyCatalogsV2, meta: { title: 'DM Dược', group: 'support' } },
  { path: 'dispensing-counter', Component: DispensingCounterV2, meta: { title: 'Quầy cấp phát thuốc', group: 'support' } },
  { path: 'clinical-pharmacy-check', Component: ClinicalPharmacyCheckV2, meta: { title: 'Dược lâm sàng kiểm tra', group: 'support' } },
  { path: 'inpatient-dispensing', Component: InpatientDispensingV2, meta: { title: 'Cấp phát nội trú', group: 'support' } },
  { path: 'stock-report', Component: StockReportV2, meta: { title: 'Báo cáo tồn kho', group: 'support' } },
  { path: 'office-supply-approval', Component: OfficeSupplyApprovalV2, meta: { title: 'Duyệt VPP', group: 'support' } },
  { path: 'lite/pharmacy', Component: PharmacyV2, meta: { title: 'Nhà thuốc (lite)', group: 'support' } },

  // --- public-health group ---
  { path: 'health-checkup', Component: HealthCheckupV2, meta: { title: 'Khám sức khoẻ', group: 'public-health' } },
  { path: 'immunization', Component: ImmunizationV2, meta: { title: 'Tiêm chủng', group: 'public-health' } },
  { path: 'epidemiology', Component: EpidemiologyV2, meta: { title: 'Giám sát dịch tễ', group: 'public-health' } },
  { path: 'school-health', Component: SchoolHealthV2, meta: { title: 'Y tế trường học', group: 'public-health' } },
  { path: 'occupational-health', Component: OccupationalHealthV2, meta: { title: 'SK nghề nghiệp', group: 'public-health' } },
  { path: 'methadone-treatment', Component: MethadoneTreatmentV2, meta: { title: 'Điều trị Methadone', group: 'public-health' } },
  { path: 'food-safety', Component: FoodSafetyV2, meta: { title: 'ATVSTP', group: 'public-health' } },
  { path: 'community-health', Component: CommunityHealthV2, meta: { title: 'SK cộng đồng', group: 'public-health' } },
  { path: 'hiv-management', Component: HivManagementV2, meta: { title: 'Quản lý HIV', group: 'public-health' } },
  { path: 'health-education', Component: HealthEducationV2, meta: { title: 'Truyền thông GDSK', group: 'public-health' } },
  { path: 'environmental-health', Component: EnvironmentalHealthV2, meta: { title: 'Môi trường y tế', group: 'public-health' } },
  { path: 'population-health', Component: PopulationHealthV2, meta: { title: 'Dân số KHHGĐ', group: 'public-health' } },
  { path: 'reproductive-health', Component: ReproductiveHealthV2, meta: { title: 'SK sinh sản', group: 'public-health' } },
  { path: 'mental-health', Component: MentalHealthV2, meta: { title: 'SK tâm thần', group: 'public-health' } },
  { path: 'trauma-registry', Component: TraumaRegistryV2, meta: { title: 'Sổ chấn thương', group: 'public-health' } },
  { path: 'medical-forensics', Component: MedicalForensicsV2, meta: { title: 'Giám định y khoa', group: 'public-health' } },
];
