import type { RouteEntry } from './index';
import {
  ReceptionV2, OPDV2, OpdEditorV2, InpatientV2, PrescriptionV2, PrescriptionEditorV2,
  SurgeryV2, EMRV2, EmrEditorV2, EmrExtractV2, EmrDataTagsV2, TelemedicineV2, FollowUpV2,
  BookingManagementV2, TreatmentProtocolV2, ChronicDiseaseV2, TbHivManagementV2, ConsultationV2,
  ClinicalCatalogsV2, SpecialtyEMRV2, MedicalRecordArchiveV2, MedicalRecordPlanningV2,
  EmergencyDisasterV2, ConsultationRegisterV2, ObservationStayV2, ServiceRequeueV2, VideoConsultationV2,
  DoctorPortalV2,
  PharmacyV2, HospitalPharmacyV2, PharmacyStockInV2, PharmacyStockIssueV2, PharmacyApprovalV2,
  PharmacyStockTakeV2, MedicalSupplyV2, NutritionV2, RehabilitationV2, TraditionalMedicineV2,
  PharmacyCatalogsV2, DispensingCounterV2, ClinicalPharmacyCheckV2, InpatientDispensingV2,
  StockReportV2, OfficeSupplyApprovalV2, EmergencyCabinetV2,
  HealthCheckupV2, ImmunizationV2, EpidemiologyV2, SchoolHealthV2, OccupationalHealthV2,
  MethadoneTreatmentV2, FoodSafetyV2, CommunityHealthV2, HivManagementV2, HealthEducationV2,
  EnvironmentalHealthV2, PopulationHealthV2, ReproductiveHealthV2, MentalHealthV2,
  TraumaRegistryV2, MedicalForensicsV2,
  TransportSlipsV2, CheckupContractsV2,
  AppointmentBookingV2,
} from '../lazy/clinical.lazy';

// Domain: clinical — menu groups clinical + support + public-health.
export const clinicalV2Routes: RouteEntry[] = [
  // --- clinical group ---
{ path: 'reception',               Component: ReceptionV2,               meta: { title: 'Tiếp đón',                  group: 'clinical',        permission: 'Reception.Read',        workspace: 'frontoffice',  module: 'TIEPDON' } },
{ path: 'opd',                     Component: OPDV2,                     meta: { title: 'Khám bệnh',                 group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'opd/edit',                Component: OpdEditorV2,               meta: { title: 'Khám bệnh',                 group: 'clinical',        permission: 'MedicalRecord.Create',  workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'ipd',                     Component: InpatientV2,               meta: { title: 'Nội trú',                   group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'NOITRU' } },
{ path: 'prescription',            Component: PrescriptionV2,            meta: { title: 'Kê đơn',                    group: 'clinical',        permission: 'Prescription.Read',     workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'prescription/edit',       Component: PrescriptionEditorV2,      meta: { title: 'Kê đơn',                    group: 'clinical',        permission: 'Prescription.Create',   workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'surgery',                 Component: SurgeryV2,                 meta: { title: 'Phẫu thuật',                group: 'clinical',        permission: 'Surgery.Read',          workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'emr',                     Component: EMRV2,                     meta: { title: 'Hồ sơ BA',                  group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'emr/edit',                Component: EmrEditorV2,               meta: { title: 'EMR',                       group: 'clinical',        permission: 'MedicalRecord.Create',  workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'emr-extract',             Component: EmrExtractV2,              meta: { title: 'Trích lục bệnh án',         group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'emr-data-tags',           Component: EmrDataTagsV2,             meta: { title: 'Thẻ dữ liệu EMR',           group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'telemedicine',            Component: TelemedicineV2,            meta: { title: 'Khám từ xa',                group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'follow-up',               Component: FollowUpV2,                meta: { title: 'Tái khám',                  group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'booking-management',      Component: BookingManagementV2,       meta: { title: 'Quản lý đặt lịch',          group: 'clinical',        permission: 'Reception.Read',        workspace: 'frontoffice',  module: 'TIEPDON' } },
{ path: 'appointment-booking',     Component: AppointmentBookingV2,      meta: { title: 'Đặt lịch hẹn',              group: 'clinical',        permission: 'Reception.Read',        workspace: 'frontoffice',  module: 'TIEPDON' } },
{ path: 'treatment-protocols',     Component: TreatmentProtocolV2,       meta: { title: 'Phác đồ điều trị',          group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'chronic-disease',         Component: ChronicDiseaseV2,          meta: { title: 'Bệnh mạn tính',             group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'tb-hiv',                  Component: TbHivManagementV2,         meta: { title: 'Quản lý Lao/HIV',           group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'consultation',            Component: ConsultationV2,            meta: { title: 'Hội chẩn',                  group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'doctor-portal',           Component: DoctorPortalV2,            meta: { title: 'Cổng bác sĩ',               group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'clinical-catalogs',       Component: ClinicalCatalogsV2,        meta: { title: 'DM Lâm sàng',               group: 'clinical',        permission: 'System.Configure',      workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'specialty-emr',           Component: SpecialtyEMRV2,            meta: { title: 'BA chuyên khoa',            group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'medical-record-archive',  Component: MedicalRecordArchiveV2,    meta: { title: 'Lưu trữ HSBA',              group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'medical-record-planning', Component: MedicalRecordPlanningV2,   meta: { title: 'Kế hoạch TH',               group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'emergency-disaster',      Component: EmergencyDisasterV2,       meta: { title: 'Cấp cứu',                   group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'consultation-register',   Component: ConsultationRegisterV2,    meta: { title: 'Sổ đăng ký hội chẩn',       group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'observation-stay',        Component: ObservationStayV2,         meta: { title: 'Lưu theo dõi',              group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'NOITRU' } },
{ path: 'service-requeue',         Component: ServiceRequeueV2,          meta: { title: 'Xếp lại hàng chờ DV',       group: 'clinical',        permission: 'MedicalRecord.Update',  workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'video-consultation',      Component: VideoConsultationV2,       meta: { title: 'Hội chẩn video',            group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'transport-slips',         Component: TransportSlipsV2,          meta: { title: 'Phiếu vận chuyển',          group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },

{ path: 'lite/reception',          Component: ReceptionV2,               meta: { title: 'Tiếp đón (lite)',           group: 'clinical',        permission: 'Reception.Read',        workspace: 'frontoffice',  module: 'TIEPDON' } },
{ path: 'lite/opd',                Component: OPDV2,                     meta: { title: 'Khám bệnh (lite)',          group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'lite/ipd',                Component: InpatientV2,               meta: { title: 'Nội trú (lite)',            group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'NOITRU' } },
{ path: 'lite/prescription',       Component: PrescriptionV2,            meta: { title: 'Kê đơn (lite)',             group: 'clinical',        permission: 'Prescription.Read',     workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'lite/surgery',            Component: SurgeryV2,                 meta: { title: 'Phẫu thuật (lite)',         group: 'clinical',        permission: 'Surgery.Read',          workspace: 'clinical',     module: 'KHAMBENH' } },
{ path: 'lite/emr',                Component: EMRV2,                     meta: { title: 'Hồ sơ BA EMR (lite)',       group: 'clinical',        permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'KHAMBENH' } },

{ path: 'pharmacy',                Component: PharmacyV2,                meta: { title: 'Nhà thuốc',                 group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'hospital-pharmacy',       Component: HospitalPharmacyV2,        meta: { title: 'Nhà thuốc bệnh viện',       group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'pharmacy-stock-in',       Component: PharmacyStockInV2,         meta: { title: 'Nhập kho NCC',              group: 'support',         permission: 'Pharmacy.StockIn',      workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'pharmacy-stock-issue',    Component: PharmacyStockIssueV2,      meta: { title: 'Xuất kho',                  group: 'support',         permission: 'Pharmacy.StockOut',     workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'pharmacy-approval',       Component: PharmacyApprovalV2,        meta: { title: 'Dự trù & Duyệt cấp phát',   group: 'support',         permission: 'Pharmacy.Approve',      workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'pharmacy-stock-take',     Component: PharmacyStockTakeV2,       meta: { title: 'Kiểm kê kho',               group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'medical-supply',          Component: MedicalSupplyV2,           meta: { title: 'Vật tư y tế',               group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'nutrition',               Component: NutritionV2,               meta: { title: 'Dinh dưỡng',                group: 'support',         permission: 'MedicalRecord.Read',    workspace: 'pharmacy',     module: 'extended' } },
{ path: 'rehabilitation',          Component: RehabilitationV2,          meta: { title: 'VLTL / PHCN',               group: 'support',         permission: 'MedicalRecord.Read',    workspace: 'pharmacy',     module: 'extended' } },
{ path: 'traditional-medicine',    Component: TraditionalMedicineV2,     meta: { title: 'Y học cổ truyền',           group: 'support',         permission: 'MedicalRecord.Read',    workspace: 'pharmacy',     module: 'extended' } },
{ path: 'pharmacy-catalogs',       Component: PharmacyCatalogsV2,        meta: { title: 'DM Dược',                   group: 'support',         permission: 'System.Configure',      workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'dispensing-counter',      Component: DispensingCounterV2,       meta: { title: 'Quầy cấp phát thuốc',       group: 'support',         permission: 'Pharmacy.Dispense',     workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'clinical-pharmacy-check', Component: ClinicalPharmacyCheckV2,   meta: { title: 'Dược lâm sàng kiểm tra',    group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'inpatient-dispensing',    Component: InpatientDispensingV2,     meta: { title: 'Cấp phát nội trú',          group: 'support',         permission: 'Pharmacy.Dispense',     workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'emergency-cabinet',       Component: EmergencyCabinetV2,        meta: { title: 'Tủ trực',                   group: 'support',         permission: 'Pharmacy.Dispense',     workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'stock-report',            Component: StockReportV2,             meta: { title: 'Báo cáo tồn kho',           group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'office-supply-approval',  Component: OfficeSupplyApprovalV2,    meta: { title: 'Duyệt VPP',                 group: 'support',         permission: 'Pharmacy.Approve',      workspace: 'pharmacy',     module: 'DUOCKHO' } },
{ path: 'lite/pharmacy',           Component: PharmacyV2,                meta: { title: 'Nhà thuốc (lite)',          group: 'support',         permission: 'Pharmacy.Read',         workspace: 'pharmacy',     module: 'DUOCKHO' } },

{ path: 'health-checkup',          Component: HealthCheckupV2,           meta: { title: 'Khám sức khoẻ',             group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'checkup-contracts',       Component: CheckupContractsV2,        meta: { title: 'Hợp đồng KSK theo đoàn',    group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'immunization',            Component: ImmunizationV2,            meta: { title: 'Tiêm chủng',                group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'epidemiology',            Component: EpidemiologyV2,            meta: { title: 'Giám sát dịch tễ',          group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'school-health',           Component: SchoolHealthV2,            meta: { title: 'Y tế trường học',           group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'occupational-health',     Component: OccupationalHealthV2,      meta: { title: 'SK nghề nghiệp',            group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'methadone-treatment',     Component: MethadoneTreatmentV2,      meta: { title: 'Điều trị Methadone',        group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'food-safety',             Component: FoodSafetyV2,              meta: { title: 'ATVSTP',                    group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'community-health',        Component: CommunityHealthV2,         meta: { title: 'SK cộng đồng',              group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'hiv-management',          Component: HivManagementV2,           meta: { title: 'Quản lý HIV',               group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'health-education',        Component: HealthEducationV2,         meta: { title: 'Truyền thông GDSK',         group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'environmental-health',    Component: EnvironmentalHealthV2,     meta: { title: 'Môi trường y tế',           group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'population-health',       Component: PopulationHealthV2,        meta: { title: 'Dân số KHHGĐ',              group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'reproductive-health',     Component: ReproductiveHealthV2,      meta: { title: 'SK sinh sản',               group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'mental-health',           Component: MentalHealthV2,            meta: { title: 'SK tâm thần',               group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'trauma-registry',         Component: TraumaRegistryV2,          meta: { title: 'Sổ chấn thương',            group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
{ path: 'medical-forensics',       Component: MedicalForensicsV2,        meta: { title: 'Giám định y khoa',          group: 'public-health',   permission: 'MedicalRecord.Read',    workspace: 'clinical',     module: 'extended' } },
];

